packages:
  - ./
  - playground/

allowUnusedPatches: true

catalog:
  '@alanscodelog/eslint-config': ^6.3.1
  '@alanscodelog/semantic-release-config': ^6.0.0
  '@alanscodelog/tsconfigs': ^6.2.0
  '@alanscodelog/utils': ^6.0.2
  '@commitlint/cli': ^20.1.0
  '@electric-sql/pglite': ~0.3.11
  '@nuxt/eslint-config': ^1.10.0
  '@nuxt/kit': ^4.2.0
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.2.0
  '@nuxt/test-utils': ^3.20.1
  '@witchcraft/nuxt-logger': ^0.0.10
  '@witchcraft/nuxt-utils': ^0.3.6
  changelogen: ^0.6.2
  cross-env: ^10.0.0
  drizzle-kit: ^0.31.6
  drizzle-orm: ^0.44.7
  eslint: ^9.34.0
  husky: ^9.1.7
  nuxt: ^4.2.0
  postgres: ^3.4.7
  typescript: ~5.9.2
  unstorage: ^1.17.0
  vite-plugin-top-level-await: ^1.6.0
  vite-plugin-wasm: ^3.5.0
  vitest: ^4.0.5
  vue-tsc: ^3.1.2
  zod: ^4.1.8

patchedDependencies:
  '@nuxt/module-builder': patches/@nuxt__module-builder.patch

settings:
  catalogMode: strict
  cleanupUnusedCatalogs: false
